In [1]:
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV
from sklearn.datasets import load_iris





In [2]:
import pandas as pd
import numpy as np
import seaborn as sns


In [ ]:
ridge = Ridge(alpha=1.0)
data= load_iris()
X = data.data
y = data.target


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [30]:

from sklearn.model_selection import train_test_split

X_train, X_test, Y_train,Y_test = train_test_split(X,y,random_state=42,test_size=0.3)
print(X_test.shape)
print(Y_test.shape)


(45, 4)
(45,)


In [37]:
ridge.fit(X_train,Y_train)
y_pred = ridge.predict(X_test)
print(y_pred)

[ 1.26704999 -0.03457202  2.25405276  1.35028686  1.31151107  0.00344623
  1.03641909  1.78417731  1.36210741  1.06762412  1.68647491 -0.07816423
 -0.16232659 -0.06422015 -0.02858721  1.40318075  1.99418384  1.05348306
  1.29676154  1.95543101  0.027774    1.58940392  0.07650647  1.90997494
  1.8904332   1.84030107  1.81459442  2.02706183  0.01274791  0.02170217
 -0.15814222 -0.07707616  1.18959087  0.00732365 -0.02843677  1.66669645
  1.29244968 -0.07052943 -0.08319453 -0.14474254  1.74103568  1.37177873
  1.3238517  -0.07972114 -0.10184444]


In [38]:
from sklearn.metrics import mean_squared_error
print("MSE:", mean_squared_error(Y_test, y_pred))

MSE: 0.040273033544016776
